"""empty message

Revision ID: 0c8ebafc065a
Revises: 
Create Date: 2023-08-31 22:55:16.000468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ebafc065a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completedAt')
    op.drop_column('tasks', 'finishUntil')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finishUntil', sa.TIMESTAMP(), nullable=False))
    op.add_column('tasks', sa.Column('completedAt', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
